import Head from 'next/head'
import Loading from '../components/Common/Loading'
import { useEffect } from 'react'
import { useRouter } from 'next/router'
import dbConnect from '../lib/dbConnect'

export default function Home() {

  const router = useRouter()
  
  useEffect(() => {
    router.push('/auth/login')
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>
          {`
            /* Other global styles such as 'html, body' etc... */

            #__next {
              height: 100%;
            }
          `}
        </style>
      </Head>
      <main style={{
        position: 'absolute',
        top: '50%',
        left: '50%'
      }}>
        <Loading />
      </main>
    </>
  )
}

export async function getStaticProps(context) {
  await dbConnect(process.env.MONGODB_URI);
  return {
    props: {}, // will be passed to the page component as props
  }
}